version: '3'

services:
  web:
    image: php:8.1-apache
    container_name: my_laravel_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel_network

  composer:
    image: composer
    container_name: composer
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - laravel_network

  db:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fima
      MYSQL_USER: fima
      MYSQL_PASSWORD: root123qwe
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network

volumes:
  db_data:

networks:
  laravel_network:
